import type { QuranicDua, DuaCategory } from "@/types/duas";

/**
 * Kur'anske dove – izvori iz Kur'ana sa tačnom referencom (sura i ajet).
 * Prijevod: Besim Korkut (Quran.com, resource_id 126) – isti kao u prikazu sura.
 * Generirano: npx tsx scripts/sync-dua-translations.ts
 */
export const QURANIC_DUAS: QuranicDua[] = [
  {
    id: "2:201",
    surahNumber: 2,
    ayahNumber: 201,
    arabic: "وَمِنْهُم مَّن يَقُولُ رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةً وَفِى ٱلْـَٔاخِرَةِ حَسَنَةً وَقِنَا عَذَابَ ٱلنَّارِ",
    transliteration: "Waminhum man yaqoolu rabbana atinafee addunya hasanatan wafee al-akhiratihasanatan waqina AAathaba annar",
    translationBosnian: "A ima i onih koji govore: \"Gospodaru naš, podaj nam dobro i na ovome i na onome svijetu, i sačuvaj nas patnje u ognju!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "2:127",
    surahNumber: 2,
    ayahNumber: 127,
    arabic: "وَإِذْ يَرْفَعُ إِبْرَٰهِـۧمُ ٱلْقَوَاعِدَ مِنَ ٱلْبَيْتِ وَإِسْمَـٰعِيلُ رَبَّنَا تَقَبَّلْ مِنَّآ ۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلْعَلِيمُ",
    transliteration: "Wa-ith yarfaAAu ibraheemualqawaAAida mina albayti wa-ismaAAeelu rabbanataqabbal minna innaka anta assameeAAu alAAaleem",
    translationBosnian: "I dok su Ibrahim i Ismail temelje Hrama podizali, oni su molili: \"Gospodaru naš, primi od nas, jer Ti, uistinu, sve čuješ i sve znaš!",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "2:128",
    surahNumber: 2,
    ayahNumber: 128,
    arabic: "رَبَّنَا وَٱجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَآ أُمَّةً مُّسْلِمَةً لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَآ ۖ إِنَّكَ أَنتَ ٱلتَّوَّابُ ٱلرَّحِيمُ",
    transliteration: "Rabbana wajAAalnamuslimayni laka wamin thurriyyatina ommatanmuslimatan laka waarina manasikana watubAAalayna innaka anta attawwabu arraheem",
    translationBosnian: "Gospodaru naš, učini nas dvojicu Tebi odanim, i porod naš neka bude odan Tebi, i pokaži nam obrede naše i oprosti nam, jer Ti primaš pokajanje i samilostan si!",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "2:250",
    surahNumber: 2,
    ayahNumber: 250,
    arabic: "وَلَمَّا بَرَزُوا۟ لِجَالُوتَ وَجُنُودِهِۦ قَالُوا۟ رَبَّنَآ أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَـٰفِرِينَ",
    transliteration: "Walamma barazoo lijalootawajunoodihi qaloo rabbana afrigh AAalayna sabranwathabbit aqdamana wansurnaAAala alqawmi alkafireen",
    translationBosnian: "I kad nastupiše prema Džalutu i vojsci njegovoj, oni zamoliše: \"Gospodaru naš, nadahni nas izdržljivošću i učvrsti korake naše i pomozi nas protiv naroda koji ne vjeruje!\"",
    category: "patience" as DuaCategory,
  },
  {
    id: "2:285",
    surahNumber: 2,
    ayahNumber: 285,
    arabic: "ءَامَنَ ٱلرَّسُولُ بِمَآ أُنزِلَ إِلَيْهِ مِن رَّبِّهِۦ وَٱلْمُؤْمِنُونَ ۚ كُلٌّ ءَامَنَ بِٱللَّهِ وَمَلَـٰٓئِكَتِهِۦ وَكُتُبِهِۦ وَرُسُلِهِۦ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِّن رُّسُلِهِۦ ۚ وَقَالُوا۟ سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ ٱلْمَصِيرُ",
    transliteration: "Amana arrasoolu bimaonzila ilayhi min rabbihi walmu/minoona kullun amanabillahi wamala-ikatihi wakutubihiwarusulihi la nufarriqu bayna ahadin min rusulihiwaqaloo samiAAna waataAAna ghufranakarabbana wa-ilayka almaseer",
    translationBosnian: "Poslanik vjeruje u ono što mu se objavljuje od Gospodara njegova, i vjernici – svaki vjeruje u Allaha, i meleke Njegove, i knjige Njegove, i poslanike Njegove: \"Mi ne izdvajamo nijednog od poslanika Njegovih.\" I oni govore: \"Čujemo i pokoravamo se; oprosti nam, Gospodaru naš; Tebi ćemo se vratiti.\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "2:286",
    surahNumber: 2,
    ayahNumber: 286,
    arabic: "لَا يُكَلِّفُ ٱللَّهُ نَفْسًا إِلَّا وُسْعَهَا ۚ لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا ٱكْتَسَبَتْ ۗ رَبَّنَا لَا تُؤَاخِذْنَآ إِن نَّسِينَآ أَوْ أَخْطَأْنَا ۚ رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَآ إِصْرًا كَمَا حَمَلْتَهُۥ عَلَى ٱلَّذِينَ مِن قَبْلِنَا ۚ رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِۦ ۖ وَٱعْفُ عَنَّا وَٱغْفِرْ لَنَا وَٱرْحَمْنَآ ۚ أَنتَ مَوْلَىٰنَا فَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَـٰفِرِينَ",
    transliteration: "La yukallifu Allahu nafsanilla wusAAaha laha ma kasabatwaAAalayha ma iktasabat rabbana latu-akhithna in naseena aw akhta/narabbana wala tahmil AAalayna isrankama hamaltahu AAala allatheena minqablina rabbana wala tuhammilnama la taqata lana bihi waAAfuAAanna waghfir lana warhamnaanta mawlana fansurna AAalaalqawmi alkafireen",
    translationBosnian: "Allah nikoga ne opterećuje preko mogućnosti njegovih: u njegovu korist je dobro koje učini, a na njegovu štetu zlo koje uradi. Gospodaru naš, ne kazni nas ako zaboravimo ili što nehotice učinimo! Gospodaru naš, ne tovari na nas breme kao što si ga tovario na one prije nas! Gospodaru naš, ne stavljaj nam u dužnost ono što ne možemo podnijeti, pobriši grijehe naše i oprosti nam, i smiluj se na nas. Ti si Gospodar naš pa nam pomozi protiv naroda koji ne vjeruje!",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:8",
    surahNumber: 3,
    ayahNumber: 8,
    arabic: "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ ٱلْوَهَّابُ",
    transliteration: "Rabbana la tuzigh quloobanabaAAda ith hadaytana wahab lana min ladunkarahmatan innaka anta alwahhab",
    translationBosnian: "\"Gospodaru naš, ne dopusti srcima našim da skrenu, kada si nam već na Pravi put ukazao, i daruj nam Svoju milost; Ti si, uistinu, Onaj koji mnogo daruje!",
    category: "guidance" as DuaCategory,
  },
  {
    id: "3:9",
    surahNumber: 3,
    ayahNumber: 9,
    arabic: "رَبَّنَآ إِنَّكَ جَامِعُ ٱلنَّاسِ لِيَوْمٍ لَّا رَيْبَ فِيهِ ۚ إِنَّ ٱللَّهَ لَا يُخْلِفُ ٱلْمِيعَادَ",
    transliteration: "Rabbana innaka jamiAAu annasiliyawmin la rayba feehi inna Allaha layukhlifu almeeAAad",
    translationBosnian: "Gospodaru naš, Ti ćeš sakupiti sve ljude na Dan u koji nema nikakve sumnje.\" – Allah će, zaista, održati obećanje.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:16",
    surahNumber: 3,
    ayahNumber: 16,
    arabic: "ٱلَّذِينَ يَقُولُونَ رَبَّنَآ إِنَّنَآ ءَامَنَّا فَٱغْفِرْ لَنَا ذُنُوبَنَا وَقِنَا عَذَابَ ٱلنَّارِ",
    transliteration: "Allatheena yaqooloona rabbanainnana amanna faghfir lana thunoobanawaqina AAathaba annar",
    translationBosnian: "oni koji budu govorili: 'Gospodaru naš, mi, zaista, vjerujemo; zato nam oprosti grijehe naše i sačuvaj nas patnje u ognju!';",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "3:38",
    surahNumber: 3,
    ayahNumber: 38,
    arabic: "هُنَالِكَ دَعَا زَكَرِيَّا رَبَّهُۥ ۖ قَالَ رَبِّ هَبْ لِى مِن لَّدُنكَ ذُرِّيَّةً طَيِّبَةً ۖ إِنَّكَ سَمِيعُ ٱلدُّعَآءِ",
    transliteration: "Hunalika daAAa zakariyyarabbahu qala rabbi hab lee min ladunka thurriyyatantayyibatan innaka sameeAAu adduAAa/-",
    translationBosnian: "Tu Zekerijja zamoli Gospodara svoga: \"Gospodaru moj\" – reče – \"podari mi od Sebe čestita potomka, jer se Ti, uistinu, molbi odazivaš!\"",
    category: "family" as DuaCategory,
  },
  {
    id: "3:53",
    surahNumber: 3,
    ayahNumber: 53,
    arabic: "رَبَّنَآ ءَامَنَّا بِمَآ أَنزَلْتَ وَٱتَّبَعْنَا ٱلرَّسُولَ فَٱكْتُبْنَا مَعَ ٱلشَّـٰهِدِينَ",
    transliteration: "Rabbana amanna bimaanzalta wattabaAAna arrasoola faktubnamaAAa ashshahideen",
    translationBosnian: "Gospodaru naš, mi u ono što Ti objavljuješ vjerujemo i mi poslanika slijedimo, zato nas upiši među vjernike!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:147",
    surahNumber: 3,
    ayahNumber: 147,
    arabic: "وَمَا كَانَ قَوْلَهُمْ إِلَّآ أَن قَالُوا۟ رَبَّنَا ٱغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِىٓ أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا وَٱنصُرْنَا عَلَى ٱلْقَوْمِ ٱلْكَـٰفِرِينَ",
    transliteration: "Wama kana qawlahum illaan qaloo rabbana ighfir lana thunoobanawa-israfana fee amrina wathabbit aqdamanawansurna AAala alqawmi alkafireen",
    translationBosnian: "i samo su govorili: \"Gospodaru naš, oprosti nam krivice naše i neumjerenost našu u postupcima našim, i učvrsti korake naše i pomozi nam protiv naroda koji ne vjeruje!\"",
    category: "patience" as DuaCategory,
  },
  {
    id: "3:191",
    surahNumber: 3,
    ayahNumber: 191,
    arabic: "ٱلَّذِينَ يَذْكُرُونَ ٱللَّهَ قِيَـٰمًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِى خَلْقِ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ رَبَّنَا مَا خَلَقْتَ هَـٰذَا بَـٰطِلًا سُبْحَـٰنَكَ فَقِنَا عَذَابَ ٱلنَّارِ",
    transliteration: "Allatheena yathkuroona Allahaqiyaman waquAAoodan waAAala junoobihimwayatafakkaroona fee khalqi assamawati wal-ardirabbana ma khalaqta hatha batilan subhanakafaqina AAathaba annar",
    translationBosnian: "za one koji i stojeći i sjedeći i ležeći Allaha spominju i o stvaranju nebesa i Zemlje razmišljaju. \"Gospodaru naš, Ti nisi ovo uzalud stvorio; hvaljen Ti budi i sačuvaj nas patnje u vatri!",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:192",
    surahNumber: 3,
    ayahNumber: 192,
    arabic: "رَبَّنَآ إِنَّكَ مَن تُدْخِلِ ٱلنَّارَ فَقَدْ أَخْزَيْتَهُۥ ۖ وَمَا لِلظَّـٰلِمِينَ مِنْ أَنصَارٍ",
    transliteration: "Rabbana innaka man tudkhili annarafaqad akhzaytahu wama liththalimeenamin ansar",
    translationBosnian: "Gospodaru naš, onoga koga Ti budeš u vatru ubacio Ti si već osramotio, a nevjernicima neće niko u pomoć priteći.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:193",
    surahNumber: 3,
    ayahNumber: 193,
    arabic: "رَّبَّنَآ إِنَّنَا سَمِعْنَا مُنَادِيًا يُنَادِى لِلْإِيمَـٰنِ أَنْ ءَامِنُوا۟ بِرَبِّكُمْ فَـَٔامَنَّا ۚ رَبَّنَا فَٱغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّـَٔاتِنَا وَتَوَفَّنَا مَعَ ٱلْأَبْرَارِ",
    transliteration: "Rabbana innana samiAAnamunadiyan yunadee lil-eemani an aminoobirabbikum faamanna rabbana faghfirlana thunoobana wakaffir AAannasayyi-atina watawaffana maAAa al-abrar",
    translationBosnian: "Gospodaru naš, mi smo čuli glasnika koji poziva u vjeru: 'Vjerujte u Gospodara vašeg!' – i mi smo mu se odazvali. Gospodaru naš, oprosti nam grijehe naše i pređi preko hrđavih postupaka naših, i učini da poslije smrti budemo s onima dobrima.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "3:194",
    surahNumber: 3,
    ayahNumber: 194,
    arabic: "رَبَّنَا وَءَاتِنَا مَا وَعَدتَّنَا عَلَىٰ رُسُلِكَ وَلَا تُخْزِنَا يَوْمَ ٱلْقِيَـٰمَةِ ۗ إِنَّكَ لَا تُخْلِفُ ٱلْمِيعَادَ",
    transliteration: "Rabbana waatina mawaAAadtana AAala rusulika wala tukhzinayawma alqiyamati innaka la tukhlifu almeeAAad",
    translationBosnian: "Gospodaru naš, podaj nam ono što si nam obećao po poslanicima Svojim i na Sudnjem danu nas ne osramoti! Ti ćeš, doista, Svoje obećanje ispuniti!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "7:23",
    surahNumber: 7,
    ayahNumber: 23,
    arabic: "قَالَا رَبَّنَا ظَلَمْنَآ أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ ٱلْخَـٰسِرِينَ",
    transliteration: "Qala rabbana thalamnaanfusana wa-in lam taghfir lana watarhamnalanakoonanna mina alkhasireen",
    translationBosnian: "\"Gospodaru naš\" – rekoše oni – \"sami smo sebi krivi, i ako nam Ti ne oprostiš i ne smiluješ nam se, sigurno ćemo biti izgubljeni.\"",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "7:47",
    surahNumber: 7,
    ayahNumber: 47,
    arabic: "۞ وَإِذَا صُرِفَتْ أَبْصَـٰرُهُمْ تِلْقَآءَ أَصْحَـٰبِ ٱلنَّارِ قَالُوا۟ رَبَّنَا لَا تَجْعَلْنَا مَعَ ٱلْقَوْمِ ٱلظَّـٰلِمِينَ",
    transliteration: "Wa-itha surifat absaruhumtilqaa as-habi annari qaloorabbana la tajAAalna maAAa alqawmi aththalimeen",
    translationBosnian: "A kada im pogledi skrenu prema stanovnicima Džehennema, uzviknuće: \"Gospodaru naš, ne daj nam da budemo s narodom grješnim!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "7:89",
    surahNumber: 7,
    ayahNumber: 89,
    arabic: "قَدِ ٱفْتَرَيْنَا عَلَى ٱللَّهِ كَذِبًا إِنْ عُدْنَا فِى مِلَّتِكُم بَعْدَ إِذْ نَجَّىٰنَا ٱللَّهُ مِنْهَا ۚ وَمَا يَكُونُ لَنَآ أَن نَّعُودَ فِيهَآ إِلَّآ أَن يَشَآءَ ٱللَّهُ رَبُّنَا ۚ وَسِعَ رَبُّنَا كُلَّ شَىْءٍ عِلْمًا ۚ عَلَى ٱللَّهِ تَوَكَّلْنَا ۚ رَبَّنَا ٱفْتَحْ بَيْنَنَا وَبَيْنَ قَوْمِنَا بِٱلْحَقِّ وَأَنتَ خَيْرُ ٱلْفَـٰتِحِينَ",
    transliteration: "Qadi iftarayna AAala Allahikathiban in AAudna fee millatikum baAAda ithnajjana Allahu minha wamayakoonu lana an naAAooda feeha illa an yashaaAllahu rabbuna wasiAAa rabbuna kulla shay-inAAilman AAala Allahi tawakkalna rabbanaiftah baynana wabayna qawmina bilhaqqiwaanta khayru alfatiheen",
    translationBosnian: "\"Ako bismo vjeru vašu prihvatili nakon što nas je Allah spasio nje, na Allaha bismo laž iznijeli. Mi je ne trebamo prihvaćati, to neće Allah, Gospodar naš, jer Gospodar naš znanjem Svojim sve obuhvaća; u Allaha se uzdamo! Gospodaru naš, Ti presudi nama i narodu našem po pravdi, Ti si sudija najpravedniji!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "7:126",
    surahNumber: 7,
    ayahNumber: 126,
    arabic: "وَمَا تَنقِمُ مِنَّآ إِلَّآ أَنْ ءَامَنَّا بِـَٔايَـٰتِ رَبِّنَا لَمَّا جَآءَتْنَا ۚ رَبَّنَآ أَفْرِغْ عَلَيْنَا صَبْرًا وَتَوَفَّنَا مُسْلِمِينَ",
    transliteration: "Wama tanqimu minna illaan amanna bi-ayati rabbinalamma jaatna rabbana afrigh AAalaynasabran watawaffana muslimeen",
    translationBosnian: "Ti nam zamjeraš samo to što smo u dokaze Gospodara našeg povjerovali kada su nam oni došli. Gospodaru naš, daj nam snage da izdržimo i učini da kao vjernici umremo!\"",
    category: "patience" as DuaCategory,
  },
  {
    id: "7:151",
    surahNumber: 7,
    ayahNumber: 151,
    arabic: "قَالَ رَبِّ ٱغْفِرْ لِى وَلِأَخِى وَأَدْخِلْنَا فِى رَحْمَتِكَ ۖ وَأَنتَ أَرْحَمُ ٱلرَّٰحِمِينَ",
    transliteration: "Qala rabbi ighfir lee wali-akheewaadkhilna fee rahmatika waanta arhamu arrahimeen",
    translationBosnian: "\"Gospodaru moj\" – zamoli Musa – \"oprosti meni i bratu mome i učini da budemo pod okriljem Tvoje milosti, Ti si od milostivih najmilostiviji!\"",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "7:155",
    surahNumber: 7,
    ayahNumber: 155,
    arabic: "وَٱخْتَارَ مُوسَىٰ قَوْمَهُۥ سَبْعِينَ رَجُلًا لِّمِيقَـٰتِنَا ۖ فَلَمَّآ أَخَذَتْهُمُ ٱلرَّجْفَةُ قَالَ رَبِّ لَوْ شِئْتَ أَهْلَكْتَهُم مِّن قَبْلُ وَإِيَّـٰىَ ۖ أَتُهْلِكُنَا بِمَا فَعَلَ ٱلسُّفَهَآءُ مِنَّآ ۖ إِنْ هِىَ إِلَّا فِتْنَتُكَ تُضِلُّ بِهَا مَن تَشَآءُ وَتَهْدِى مَن تَشَآءُ ۖ أَنتَ وَلِيُّنَا فَٱغْفِرْ لَنَا وَٱرْحَمْنَا ۖ وَأَنتَ خَيْرُ ٱلْغَـٰفِرِينَ",
    transliteration: "Wakhtara moosaqawmahu sabAAeena rajulan limeeqatina falammaakhathat-humu arrajfatu qala rabbi lawshi/ta ahlaktahum min qablu wa-iyyaya atuhlikunabima faAAala assufahao minna in hiyailla fitnatuka tudillu biha man tashaowatahdee man tashao anta waliyyuna faghfirlana warhamna waanta khayru alghafireen",
    translationBosnian: "I Musa odabra iz naroda svoga sedamdeset ljudi da u određeno vrijeme stanu pred Nas. A kad ih zadesi potres, on reče: \"Gospodaru moj, da si htio, mogao si i njih i mene uništiti još prije. Zar da nas uništiš zbog onoga što su uradili bezumnici naši? To je samo iskušenje Tvoje kojim Ti, koga hoćeš, u zabludi ostavljaš, a kome hoćeš, na Pravi put ukazuješ; Ti si Gospodar naš, pa nam oprosti i smiluj nam se, jer Ti praštaš najviše;",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "10:85",
    surahNumber: 10,
    ayahNumber: 85,
    arabic: "فَقَالُوا۟ عَلَى ٱللَّهِ تَوَكَّلْنَا رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلْقَوْمِ ٱلظَّـٰلِمِينَ",
    transliteration: "Faqaloo AAala Allahitawakkalna rabbana la tajAAalnafitnatan lilqawmi aththalimeen",
    translationBosnian: "\"U Allaha se uzdamo!\" – rekoše oni. \"Gospodaru naš, ne učini da zbog nas dođu u iskušenje ljudi koji nasilje čine,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "10:86",
    surahNumber: 10,
    ayahNumber: 86,
    arabic: "وَنَجِّنَا بِرَحْمَتِكَ مِنَ ٱلْقَوْمِ ٱلْكَـٰفِرِينَ",
    transliteration: "Wanajjina birahmatika minaalqawmi alkafireen",
    translationBosnian: "i spasi nas, milošću Svojom, od naroda koji ne vjeruje!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "11:47",
    surahNumber: 11,
    ayahNumber: 47,
    arabic: "قَالَ رَبِّ إِنِّىٓ أَعُوذُ بِكَ أَنْ أَسْـَٔلَكَ مَا لَيْسَ لِى بِهِۦ عِلْمٌ ۖ وَإِلَّا تَغْفِرْ لِى وَتَرْحَمْنِىٓ أَكُن مِّنَ ٱلْخَـٰسِرِينَ",
    transliteration: "Qala rabbi innee aAAoothu bikaan as-alaka ma laysa lee bihi AAilmun wa-illataghfir lee watarhamnee akun mina alkhasireen",
    translationBosnian: "\"Gospodaru moj\" – reče – \"Tebi se ja utječem da Te više nikad ne zamolim za ono što ne znam! Ako mi ne oprostiš i ne smiluješ mi se, biću izgubljen.\"",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "12:101",
    surahNumber: 12,
    ayahNumber: 101,
    arabic: "۞ رَبِّ قَدْ ءَاتَيْتَنِى مِنَ ٱلْمُلْكِ وَعَلَّمْتَنِى مِن تَأْوِيلِ ٱلْأَحَادِيثِ ۚ فَاطِرَ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ أَنتَ وَلِىِّۦ فِى ٱلدُّنْيَا وَٱلْـَٔاخِرَةِ ۖ تَوَفَّنِى مُسْلِمًا وَأَلْحِقْنِى بِٱلصَّـٰلِحِينَ",
    transliteration: "Rabbi qad ataytanee mina almulkiwaAAallamtanee min ta/weeli al-ahadeethi fatira assamawatiwal-ardi anta waliyyee fee addunyawal-akhirati tawaffanee musliman waalhiqneebissaliheen",
    translationBosnian: "Gospodaru moj, Ti si mi dao dio vlasti i naučio me tumačenju nekih snova! O Stvoritelju nebesa i Zemlje, Ti si Zaštitnik moj i na ovome i na onome svijetu; daj da umrem kao musliman i pridruži me onima koji su dobri!\"",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "14:35",
    surahNumber: 14,
    ayahNumber: 35,
    arabic: "وَإِذْ قَالَ إِبْرَٰهِيمُ رَبِّ ٱجْعَلْ هَـٰذَا ٱلْبَلَدَ ءَامِنًا وَٱجْنُبْنِى وَبَنِىَّ أَن نَّعْبُدَ ٱلْأَصْنَامَ",
    transliteration: "Wa-ith qala ibraheemurabbi ijAAal hatha albalada aminan wajnubneewabaniyya an naAAbuda al-asnam",
    translationBosnian: "A kada Ibrahim reče: \"Gospodaru moj, učini ovaj grad sigurnim i sačuvaj mene i sinove moje da se klanjamo kumirima,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "14:40",
    surahNumber: 14,
    ayahNumber: 40,
    arabic: "رَبِّ ٱجْعَلْنِى مُقِيمَ ٱلصَّلَوٰةِ وَمِن ذُرِّيَّتِى ۚ رَبَّنَا وَتَقَبَّلْ دُعَآءِ",
    transliteration: "Rabbi ijAAalnee muqeema assalatiwamin thurriyyatee rabbana wtaqabbal duAAa/-",
    translationBosnian: "Gospodaru moj, daj da ja i neki potomci moji obavljamo molitvu; Gospodaru naš, Ti usliši molbu moju!",
    category: "family" as DuaCategory,
  },
  {
    id: "14:41",
    surahNumber: 14,
    ayahNumber: 41,
    arabic: "رَبَّنَا ٱغْفِرْ لِى وَلِوَٰلِدَىَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ ٱلْحِسَابُ",
    transliteration: "Rabbana ighfir lee waliwalidayyawalilmu/mineena yawma yaqoomu alhisab",
    translationBosnian: "Gospodaru naš, oprosti meni, i roditeljima mojim, i svim vjernicima – na Dan kad se bude polagao račun!\"",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "17:24",
    surahNumber: 17,
    ayahNumber: 24,
    arabic: "وَٱخْفِضْ لَهُمَا جَنَاحَ ٱلذُّلِّ مِنَ ٱلرَّحْمَةِ وَقُل رَّبِّ ٱرْحَمْهُمَا كَمَا رَبَّيَانِى صَغِيرًا",
    transliteration: "Wakhfid lahuma janahaaththulli mina arrahmati waqulrabbi irhamhuma kama rabbayanee sagheera",
    translationBosnian: "Budi prema njima pažljiv i ponizan i reci: \"Gospodaru moj, smiluj im se, oni su mene, kad sam bio dijete, njegovali!\"",
    category: "family" as DuaCategory,
  },
  {
    id: "17:80",
    surahNumber: 17,
    ayahNumber: 80,
    arabic: "وَقُل رَّبِّ أَدْخِلْنِى مُدْخَلَ صِدْقٍ وَأَخْرِجْنِى مُخْرَجَ صِدْقٍ وَٱجْعَل لِّى مِن لَّدُنكَ سُلْطَـٰنًا نَّصِيرًا",
    transliteration: "Waqul rabbi adkhilnee mudkhala sidqinwaakhrijnee mukhraja sidqin wajAAal lee minladunka sultanan naseera",
    translationBosnian: "I reci: \"Gospodaru moj, učini da umrem, a da si Ti zadovoljan mnome i učini da iz mrtvih ustanem, a da si Ti zadovoljan mnome, i daruj mi od Sebe snagu koja će mi pomoći!\"",
    category: "guidance" as DuaCategory,
  },
  {
    id: "18:10",
    surahNumber: 18,
    ayahNumber: 10,
    arabic: "إِذْ أَوَى ٱلْفِتْيَةُ إِلَى ٱلْكَهْفِ فَقَالُوا۟ رَبَّنَآ ءَاتِنَا مِن لَّدُنكَ رَحْمَةً وَهَيِّئْ لَنَا مِنْ أَمْرِنَا رَشَدًا",
    transliteration: "Ith awa alfityatu ilaalkahfi faqaloo rabbana atina minladunka rahmatan wahayyi/ lana min amrinarashada",
    translationBosnian: "Kad se nekoliko momaka u pećini sklonilo pa reklo: \"Gospodaru naš, daj nam Svoju milost i pruži nam u ovom našem postupku prisebnost\",",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "19:4",
    surahNumber: 19,
    ayahNumber: 4,
    arabic: "قَالَ رَبِّ إِنِّى وَهَنَ ٱلْعَظْمُ مِنِّى وَٱشْتَعَلَ ٱلرَّأْسُ شَيْبًا وَلَمْ أَكُنۢ بِدُعَآئِكَ رَبِّ شَقِيًّا",
    transliteration: "Qala rabbi innee wahana alAAathmuminnee washtaAAala arra/su shayban walam akunbiduAAa-ika rabbi shaqiyya",
    translationBosnian: "i rekao: \"Gospodaru moj, kosti su mi oronule i glava osijedjela, a nikada nisam, kad sam Ti, Gospodaru moj, molbu uputio, nesretan ostao.",
    category: "family" as DuaCategory,
  },
  {
    id: "19:5",
    surahNumber: 19,
    ayahNumber: 5,
    arabic: "وَإِنِّى خِفْتُ ٱلْمَوَٰلِىَ مِن وَرَآءِى وَكَانَتِ ٱمْرَأَتِى عَاقِرًا فَهَبْ لِى مِن لَّدُنكَ وَلِيًّا",
    transliteration: "Wa-innee khiftu almawaliya min wara-eewakanati imraatee AAaqiran fahab lee min ladunkawaliyya",
    translationBosnian: "Bojim se rođaka svojih po krvi poslije mene, a žena mi je nerotkinja, zato mi pokloni od Sebe sina",
    category: "family" as DuaCategory,
  },
  {
    id: "20:25",
    surahNumber: 20,
    ayahNumber: 25,
    arabic: "قَالَ رَبِّ ٱشْرَحْ لِى صَدْرِى",
    transliteration: "Qala rabbi ishrah lee sadree",
    translationBosnian: "\"Gospodaru moj\" – reče Musa – \"učini prostranim prsa moja",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "20:26",
    surahNumber: 20,
    ayahNumber: 26,
    arabic: "وَيَسِّرْ لِىٓ أَمْرِى",
    transliteration: "Wayassir lee amree",
    translationBosnian: "i olakšaj zadatak moj;",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "20:27",
    surahNumber: 20,
    ayahNumber: 27,
    arabic: "وَٱحْلُلْ عُقْدَةً مِّن لِّسَانِى",
    transliteration: "Wahlul AAuqdatan min lisanee",
    translationBosnian: "odriješi uzao sa jezika moga",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "20:28",
    surahNumber: 20,
    ayahNumber: 28,
    arabic: "يَفْقَهُوا۟ قَوْلِى",
    transliteration: "Yafqahoo qawlee",
    translationBosnian: "da bi razumjeli govor moj",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "20:114",
    surahNumber: 20,
    ayahNumber: 114,
    arabic: "فَتَعَـٰلَى ٱللَّهُ ٱلْمَلِكُ ٱلْحَقُّ ۗ وَلَا تَعْجَلْ بِٱلْقُرْءَانِ مِن قَبْلِ أَن يُقْضَىٰٓ إِلَيْكَ وَحْيُهُۥ ۖ وَقُل رَّبِّ زِدْنِى عِلْمًا",
    transliteration: "FataAAala Allahualmaliku alhaqqu wala taAAjal bilqur-animin qabli an yuqda ilayka wahyuhu waqul rabbizidnee AAilma",
    translationBosnian: "Neka je uzvišen Allah, Vladar Istiniti! I ne žuri s čitanjem Kur'ana prije nego što ti se objavljivanje njegovo ne završi, i reci: \"Gospodaru moj, Ti znanje moje proširi!\"",
    category: "knowledge" as DuaCategory,
  },
  {
    id: "21:83",
    surahNumber: 21,
    ayahNumber: 83,
    arabic: "۞ وَأَيُّوبَ إِذْ نَادَىٰ رَبَّهُۥٓ أَنِّى مَسَّنِىَ ٱلضُّرُّ وَأَنتَ أَرْحَمُ ٱلرَّٰحِمِينَ",
    transliteration: "Waayyooba ith nadarabbahu annee massaniya addurru waanta arhamuarrahimeen",
    translationBosnian: "I Ejjubu se, kada je Gospodaru svome zavapio: \"Mene je nevolja snašla, a Ti si od milostivih najmilostiviji!\" –",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "21:87",
    surahNumber: 21,
    ayahNumber: 87,
    arabic: "وَذَا ٱلنُّونِ إِذ ذَّهَبَ مُغَـٰضِبًا فَظَنَّ أَن لَّن نَّقْدِرَ عَلَيْهِ فَنَادَىٰ فِى ٱلظُّلُمَـٰتِ أَن لَّآ إِلَـٰهَ إِلَّآ أَنتَ سُبْحَـٰنَكَ إِنِّى كُنتُ مِنَ ٱلظَّـٰلِمِينَ",
    transliteration: "Watha annooni ith thahabamughadiban fathanna an lan naqdira AAalayhifanada fee aththulumatian la ilaha illa anta subhanaka inneekuntu mina aththalimeen",
    translationBosnian: "I Zunnunu se, kada srdit ode i pomisli da ga nećemo kazniti – pa poslije u tminama zavapi: \"Nema boga osim Tebe, hvaljen neka si, a ja sam se zaista ogriješio prema sebi!\" –",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "21:89",
    surahNumber: 21,
    ayahNumber: 89,
    arabic: "وَزَكَرِيَّآ إِذْ نَادَىٰ رَبَّهُۥ رَبِّ لَا تَذَرْنِى فَرْدًا وَأَنتَ خَيْرُ ٱلْوَٰرِثِينَ",
    transliteration: "Wazakariyya ith nadarabbahu rabbi la tatharnee fardan waanta khayru alwaritheen",
    translationBosnian: "I Zekerijjau se – kada zamoli Gospodara svoga: \"Gospodaru moj, ne ostavljaj me sama, a Ti si jedini vječan!\" –",
    category: "family" as DuaCategory,
  },
  {
    id: "23:29",
    surahNumber: 23,
    ayahNumber: 29,
    arabic: "وَقُل رَّبِّ أَنزِلْنِى مُنزَلًا مُّبَارَكًا وَأَنتَ خَيْرُ ٱلْمُنزِلِينَ",
    transliteration: "Waqul rabbi anzilnee munzalan mubarakanwaanta khayru almunzileen",
    translationBosnian: "I reci: 'Gospodaru moj, iskrcaj me na blagoslovljeno mjesto, Ti to najbolje umiješ!'\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "23:97",
    surahNumber: 23,
    ayahNumber: 97,
    arabic: "وَقُل رَّبِّ أَعُوذُ بِكَ مِنْ هَمَزَٰتِ ٱلشَّيَـٰطِينِ",
    transliteration: "Waqul rabbi aAAoothu bika min hamazatiashshayateen",
    translationBosnian: "i reci: \"Tebi se ja, Gospodaru moj, obraćam za zaštitu od priviđenja šejtanskih,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "23:98",
    surahNumber: 23,
    ayahNumber: 98,
    arabic: "وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ",
    transliteration: "WaaAAoothu bika rabbi an yahduroon",
    translationBosnian: "i Tebi se, Gospodaru moj, obraćam da me od njihova prisustva zaštitiš!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "23:109",
    surahNumber: 23,
    ayahNumber: 109,
    arabic: "إِنَّهُۥ كَانَ فَرِيقٌ مِّنْ عِبَادِى يَقُولُونَ رَبَّنَآ ءَامَنَّا فَٱغْفِرْ لَنَا وَٱرْحَمْنَا وَأَنتَ خَيْرُ ٱلرَّٰحِمِينَ",
    transliteration: "Innahu kana fareequn min AAibadeeyaqooloona rabbana amanna faghfirlana warhamna waanta khayru arrahimeen",
    translationBosnian: "\"Kad su neki robovi Moji govorili: 'Gospodaru naš, mi vjerujemo, zato nam oprosti i smiluj nam se, jer Ti si najmilostiviji!' –",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "23:118",
    surahNumber: 23,
    ayahNumber: 118,
    arabic: "وَقُل رَّبِّ ٱغْفِرْ وَٱرْحَمْ وَأَنتَ خَيْرُ ٱلرَّٰحِمِينَ",
    transliteration: "Waqul rabbi ighfir warhamwaanta khayru arrahimeen",
    translationBosnian: "I reci: \"Gospodaru moj, oprosti i smiluj se, Ti si najmilostiviji!\"",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "25:74",
    surahNumber: 25,
    ayahNumber: 74,
    arabic: "وَٱلَّذِينَ يَقُولُونَ رَبَّنَا هَبْ لَنَا مِنْ أَزْوَٰجِنَا وَذُرِّيَّـٰتِنَا قُرَّةَ أَعْيُنٍ وَٱجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    transliteration: "Wallatheena yaqooloona rabbanahab lana min azwajina wathurriyyatinaqurrata aAAyunin wajAAalna lilmuttaqeena imama",
    translationBosnian: "i oni koji govore: \"Gospodaru naš, podari nam u ženama našim i djeci našoj radost i učini da se čestiti na nas ugledaju!\" –",
    category: "family" as DuaCategory,
  },
  {
    id: "26:83",
    surahNumber: 26,
    ayahNumber: 83,
    arabic: "رَبِّ هَبْ لِى حُكْمًا وَأَلْحِقْنِى بِٱلصَّـٰلِحِينَ",
    transliteration: "Rabbi hab lee hukman waalhiqneebissaliheen",
    translationBosnian: "Gospodaru moj, podari mi mudrost i uvrsti me među one koji su dobri",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:84",
    surahNumber: 26,
    ayahNumber: 84,
    arabic: "وَٱجْعَل لِّى لِسَانَ صِدْقٍ فِى ٱلْـَٔاخِرِينَ",
    transliteration: "WajAAal lee lisana sidqinfee al-akhireen",
    translationBosnian: "i učini da me po lijepom spominju oni što će poslije mene doći,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:85",
    surahNumber: 26,
    ayahNumber: 85,
    arabic: "وَٱجْعَلْنِى مِن وَرَثَةِ جَنَّةِ ٱلنَّعِيمِ",
    transliteration: "WajAAalnee min warathati jannati annaAAeem",
    translationBosnian: "i učini me jednim od onih kojima ćeš džennetske blagodati darovati –",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:86",
    surahNumber: 26,
    ayahNumber: 86,
    arabic: "وَٱغْفِرْ لِأَبِىٓ إِنَّهُۥ كَانَ مِنَ ٱلضَّآلِّينَ",
    transliteration: "Waghfir li-abee innahu kanamina addalleen",
    translationBosnian: "i ocu mome oprosti, on je jedan od zalutalih –",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "26:87",
    surahNumber: 26,
    ayahNumber: 87,
    arabic: "وَلَا تُخْزِنِى يَوْمَ يُبْعَثُونَ",
    transliteration: "Wala tukhzinee yawma yubAAathoon",
    translationBosnian: "i ne osramoti me na Dan kad će ljudi oživljeni biti,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:88",
    surahNumber: 26,
    ayahNumber: 88,
    arabic: "يَوْمَ لَا يَنفَعُ مَالٌ وَلَا بَنُونَ",
    transliteration: "Yawma la yanfaAAu malun walabanoon",
    translationBosnian: "na Dan kada neće nikakvo blago, a ni sinovi od koristi biti,",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:89",
    surahNumber: 26,
    ayahNumber: 89,
    arabic: "إِلَّا مَنْ أَتَى ٱللَّهَ بِقَلْبٍ سَلِيمٍ",
    transliteration: "Illa man ata Allahabiqalbin saleem",
    translationBosnian: "samo će onaj koji Allahu srca čista dođe spašen biti.\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "26:169",
    surahNumber: 26,
    ayahNumber: 169,
    arabic: "رَبِّ نَجِّنِى وَأَهْلِى مِمَّا يَعْمَلُونَ",
    transliteration: "Rabbi najjinee waahlee mimmayaAAmaloon",
    translationBosnian: "\"Gospodaru moj, sačuvaj mene i porodicu moju kazne za ono što oni rade!\"",
    category: "family" as DuaCategory,
  },
  {
    id: "27:19",
    surahNumber: 27,
    ayahNumber: 19,
    arabic: "فَتَبَسَّمَ ضَاحِكًا مِّن قَوْلِهَا وَقَالَ رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِىٓ أَنْعَمْتَ عَلَىَّ وَعَلَىٰ وَٰلِدَىَّ وَأَنْ أَعْمَلَ صَـٰلِحًا تَرْضَىٰهُ وَأَدْخِلْنِى بِرَحْمَتِكَ فِى عِبَادِكَ ٱلصَّـٰلِحِينَ",
    transliteration: "Fatabassama dahikan min qawlihawaqala rabbi awziAAnee an ashkura niAAmataka allateeanAAamta AAalayya waAAala walidayya waan aAAmala salihantardahu waadkhilnee birahmatika fee AAibadikaassaliheen",
    translationBosnian: "I on se nasmija glasno riječima njegovim i reče: \"Gospodaru moj, omogući mi da budem zahvalan na blagodati Tvojoj, koju si ukazao meni i roditeljima mojim, i da činim dobra djela na zadovoljstvo Tvoje, i uvedi me, milošću Svojom, među dobre robove Svoje!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "28:16",
    surahNumber: 28,
    ayahNumber: 16,
    arabic: "قَالَ رَبِّ إِنِّى ظَلَمْتُ نَفْسِى فَٱغْفِرْ لِى فَغَفَرَ لَهُۥٓ ۚ إِنَّهُۥ هُوَ ٱلْغَفُورُ ٱلرَّحِيمُ",
    transliteration: "Qala rabbi innee thalamtunafsee faghfir lee faghafara lahu innahu huwa alghafooruarraheem",
    translationBosnian: "Gospodaru moj\" – reče onda – \"ja sam sâm sebi zlo nanio, oprosti mi!\" I On mu oprosti, On, uistinu, prašta i On je milostiv.",
    category: "forgiveness" as DuaCategory,
  },
  {
    id: "28:24",
    surahNumber: 28,
    ayahNumber: 24,
    arabic: "فَسَقَىٰ لَهُمَا ثُمَّ تَوَلَّىٰٓ إِلَى ٱلظِّلِّ فَقَالَ رَبِّ إِنِّى لِمَآ أَنزَلْتَ إِلَىَّ مِنْ خَيْرٍ فَقِيرٌ",
    transliteration: "Fasaqa lahuma thumma tawallaila aththilli faqala rabbiinnee lima anzalta ilayya min khayrin faqeer",
    translationBosnian: "I on im je napoji, a onda ode u hladovinu i reče: \"Gospodaru moj, ma kakvu mi hranu dao, zaista mi je potrebna!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "29:30",
    surahNumber: 29,
    ayahNumber: 30,
    arabic: "قَالَ رَبِّ ٱنصُرْنِى عَلَى ٱلْقَوْمِ ٱلْمُفْسِدِينَ",
    transliteration: "Qala rabbi onsurnee AAalaalqawmi almufsideen",
    translationBosnian: "\"Gospodaru moj\" – reče on – \"pomozi mi protiv naroda grješnog!\"",
    category: "patience" as DuaCategory,
  },
  {
    id: "40:7",
    surahNumber: 40,
    ayahNumber: 7,
    arabic: "ٱلَّذِينَ يَحْمِلُونَ ٱلْعَرْشَ وَمَنْ حَوْلَهُۥ يُسَبِّحُونَ بِحَمْدِ رَبِّهِمْ وَيُؤْمِنُونَ بِهِۦ وَيَسْتَغْفِرُونَ لِلَّذِينَ ءَامَنُوا۟ رَبَّنَا وَسِعْتَ كُلَّ شَىْءٍ رَّحْمَةً وَعِلْمًا فَٱغْفِرْ لِلَّذِينَ تَابُوا۟ وَٱتَّبَعُوا۟ سَبِيلَكَ وَقِهِمْ عَذَابَ ٱلْجَحِيمِ",
    transliteration: "Allatheena yahmiloona alAAarshawaman hawlahu yusabbihoona bihamdi rabbihimwayu/minoona bihi wayastaghfiroona lillatheena amanoorabbana wasiAAta kulla shay-in rahmatan waAAilmanfaghfir lillatheena taboo wattabaAAoosabeelaka waqihim AAathaba aljaheem",
    translationBosnian: "Meleki koji drže Prijesto i oni koji su oko njega veličaju i hvale Gospodara svoga i vjeruju u Nj i mole se da budu oprošteni grijesi vjernicima: \"Gospodaru naš, Ti sve obuhvaćaš milošću i znanjem; zato oprosti onima koji su se pokajali i koji slijede Tvoj put i sačuvaj ih patnje u vatri!",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "40:8",
    surahNumber: 40,
    ayahNumber: 8,
    arabic: "رَبَّنَا وَأَدْخِلْهُمْ جَنَّـٰتِ عَدْنٍ ٱلَّتِى وَعَدتَّهُمْ وَمَن صَلَحَ مِنْ ءَابَآئِهِمْ وَأَزْوَٰجِهِمْ وَذُرِّيَّـٰتِهِمْ ۚ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ",
    transliteration: "Rabbana waadkhilhum jannatiAAadnin allatee waAAadtahum waman salaha min aba-ihimwaazwajihim wathurriyyatihim innaka antaalAAazeezu alhakeem",
    translationBosnian: "Gospodaru naš, uvedi ih u edenske vrtove, koje si im obećao, i pretke njihove i žene njihove i potomstvo njihovo – one koji su bili dobri; Ti si, uistinu, silan i mudar.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "40:9",
    surahNumber: 40,
    ayahNumber: 9,
    arabic: "وَقِهِمُ ٱلسَّيِّـَٔاتِ ۚ وَمَن تَقِ ٱلسَّيِّـَٔاتِ يَوْمَئِذٍ فَقَدْ رَحِمْتَهُۥ ۚ وَذَٰلِكَ هُوَ ٱلْفَوْزُ ٱلْعَظِيمُ",
    transliteration: "Waqihimu assayyi-ati wamantaqi assayyi-ati yawma-ithin faqad rahimtahuwathalika huwa alfawzu alAAatheem",
    translationBosnian: "I poštedi ih kazne zbog ružnih djela, jer koga Ti toga dana poštediš kazne zbog ružnih djela – Ti si mu se smilovao, a to će, zaista, veliki uspjeh biti!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "44:12",
    surahNumber: 44,
    ayahNumber: 12,
    arabic: "رَّبَّنَا ٱكْشِفْ عَنَّا ٱلْعَذَابَ إِنَّا مُؤْمِنُونَ",
    transliteration: "Rabbana ikshif AAanna alAAathabainna mu/minoon",
    translationBosnian: "Gospodaru naš, otkloni patnju od nas, mi ćemo, sigurno, vjerovati!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "46:15",
    surahNumber: 46,
    ayahNumber: 15,
    arabic: "وَوَصَّيْنَا ٱلْإِنسَـٰنَ بِوَٰلِدَيْهِ إِحْسَـٰنًا ۖ حَمَلَتْهُ أُمُّهُۥ كُرْهًا وَوَضَعَتْهُ كُرْهًا ۖ وَحَمْلُهُۥ وَفِصَـٰلُهُۥ ثَلَـٰثُونَ شَهْرًا ۚ حَتَّىٰٓ إِذَا بَلَغَ أَشُدَّهُۥ وَبَلَغَ أَرْبَعِينَ سَنَةً قَالَ رَبِّ أَوْزِعْنِىٓ أَنْ أَشْكُرَ نِعْمَتَكَ ٱلَّتِىٓ أَنْعَمْتَ عَلَىَّ وَعَلَىٰ وَٰلِدَىَّ وَأَنْ أَعْمَلَ صَـٰلِحًا تَرْضَىٰهُ وَأَصْلِحْ لِى فِى ذُرِّيَّتِىٓ ۖ إِنِّى تُبْتُ إِلَيْكَ وَإِنِّى مِنَ ٱلْمُسْلِمِينَ",
    transliteration: "Wawassayna al-insanabiwalidayhi ihsanan hamalat-hu ommuhukurhan wawadaAAat-hu kurhan wahamluhu wafisaluhuthalathoona shahran hatta ithabalagha ashuddahu wabalagha arbaAAeena sanatan qala rabbiawziAAnee an ashkura niAAmataka allatee anAAamta AAalayya waAAalawalidayya waan aAAmala salihan tardahuwaaslih lee fee thurriyyatee innee tubtuilayka wa-innee mina almuslimeen",
    translationBosnian: "Čovjeka smo zadužili da roditeljima svojim čini dobro; majka njegova s mukom ga nosi i u mukama ga rađa, nosi ga i doji trideset mjeseci. A kad dospije u muževno doba i kad dostigne četrdeset godina, on rekne: \"Gospodaru moj, dozvoli Mi da Ti budem zahvalan na blagodati koju si darovao meni i roditeljima mojim, i pomozi mi da činim dobra djela kojima ćeš zadovoljan biti, i učini dobrim potomke moje; ja se, zaista, kajem i odan sam Tebi.\"",
    category: "family" as DuaCategory,
  },
  {
    id: "59:10",
    surahNumber: 59,
    ayahNumber: 10,
    arabic: "وَٱلَّذِينَ جَآءُو مِنۢ بَعْدِهِمْ يَقُولُونَ رَبَّنَا ٱغْفِرْ لَنَا وَلِإِخْوَٰنِنَا ٱلَّذِينَ سَبَقُونَا بِٱلْإِيمَـٰنِ وَلَا تَجْعَلْ فِى قُلُوبِنَا غِلًّا لِّلَّذِينَ ءَامَنُوا۟ رَبَّنَآ إِنَّكَ رَءُوفٌ رَّحِيمٌ",
    transliteration: "Wallatheena jaoo minbaAAdihim yaqooloona rabbana ighfir lana wali-ikhwaninaallatheena sabaqoona bil-eemani walatajAAal fee quloobina ghillan lillatheena amanoorabbana innaka raoofun raheem",
    translationBosnian: "Oni koji poslije njih dolaze – govore: \"Gospodaru naš, oprosti nama i braći našoj koja su nas u vjeri pretekla i ne dopusti da u srcima našim bude imalo zlobe prema vjernicima; Gospodaru naš, ti si, zaista, dobar i milostiv!\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "60:4",
    surahNumber: 60,
    ayahNumber: 4,
    arabic: "قَدْ كَانَتْ لَكُمْ أُسْوَةٌ حَسَنَةٌ فِىٓ إِبْرَٰهِيمَ وَٱلَّذِينَ مَعَهُۥٓ إِذْ قَالُوا۟ لِقَوْمِهِمْ إِنَّا بُرَءَٰٓؤُا۟ مِنكُمْ وَمِمَّا تَعْبُدُونَ مِن دُونِ ٱللَّهِ كَفَرْنَا بِكُمْ وَبَدَا بَيْنَنَا وَبَيْنَكُمُ ٱلْعَدَٰوَةُ وَٱلْبَغْضَآءُ أَبَدًا حَتَّىٰ تُؤْمِنُوا۟ بِٱللَّهِ وَحْدَهُۥٓ إِلَّا قَوْلَ إِبْرَٰهِيمَ لِأَبِيهِ لَأَسْتَغْفِرَنَّ لَكَ وَمَآ أَمْلِكُ لَكَ مِنَ ٱللَّهِ مِن شَىْءٍ ۖ رَّبَّنَا عَلَيْكَ تَوَكَّلْنَا وَإِلَيْكَ أَنَبْنَا وَإِلَيْكَ ٱلْمَصِيرُ",
    transliteration: "Qad kanat lakum oswatun hasanatunfee ibraheema wallatheena maAAahu ithqaloo liqawmihim inna buraao minkum wamimmataAAbudoona min dooni Allahi kafarna bikum wabadabaynana wabaynakumu alAAadawatu walbaghdaoabadan hatta tu/minoo billahi wahdahuilla qawla ibraheema li-abeehi laastaghfiranna lakawama amliku laka mina Allahi min shay-in rabbanaAAalayka tawakkalna wa-ilayka anabna wa-ilayka almaseer",
    translationBosnian: "Divan uzor za vas je Ibrahim i oni koji su uz njega bili kada su narodu svome rekli: \"Mi s vama nemamo ništa, a ni sa onima kojima se, umjesto Allahu, klanjate; mi vas se odričemo, i neprijateljstvo i mržnja će između nas ostati sve dok ne budete u Allaha, Njega jedinog, vjerovali!\" – ali nisu riječi Ibrahimove ocu svome: \"Ja ću se moliti da ti oprosti, ali te ne mogu od Allaha odbraniti.\" – Gospodaru naš, u Tebe se uzdamo i Tebi se obraćamo i Tebi ćemo se vratiti.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "60:5",
    surahNumber: 60,
    ayahNumber: 5,
    arabic: "رَبَّنَا لَا تَجْعَلْنَا فِتْنَةً لِّلَّذِينَ كَفَرُوا۟ وَٱغْفِرْ لَنَا رَبَّنَآ ۖ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ",
    transliteration: "Rabbana la tajAAalnafitnatan lillatheena kafaroo waghfir lanarabbana innaka anta alAAazeezu alhakeem",
    translationBosnian: "Ne dopusti, Gospodaru naš, da nas nevjernicima staviš u iskušenje i oprosti nam, Gospodaru naš! Ti si, zaista, Silni i Mudri.",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "66:8",
    surahNumber: 66,
    ayahNumber: 8,
    arabic: "يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ تُوبُوٓا۟ إِلَى ٱللَّهِ تَوْبَةً نَّصُوحًا عَسَىٰ رَبُّكُمْ أَن يُكَفِّرَ عَنكُمْ سَيِّـَٔاتِكُمْ وَيُدْخِلَكُمْ جَنَّـٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَـٰرُ يَوْمَ لَا يُخْزِى ٱللَّهُ ٱلنَّبِىَّ وَٱلَّذِينَ ءَامَنُوا۟ مَعَهُۥ ۖ نُورُهُمْ يَسْعَىٰ بَيْنَ أَيْدِيهِمْ وَبِأَيْمَـٰنِهِمْ يَقُولُونَ رَبَّنَآ أَتْمِمْ لَنَا نُورَنَا وَٱغْفِرْ لَنَآ ۖ إِنَّكَ عَلَىٰ كُلِّ شَىْءٍ قَدِيرٌ",
    transliteration: "Ya ayyuha allatheena amanootooboo ila Allahi tawbatan nasoohanAAasa rabbukum an yukaffira AAankum sayyi-atikumwayudkhilakum jannatin tajree min tahtihaal-anharu yawma la yukhzee Allahu annabiyyawallatheena amanoo maAAahu nooruhum yasAAabayna aydeehim wabi-aymanihim yaqooloona rabbanaatmim lana noorana waghfir lanainnaka AAala kulli shay-in qadeer",
    translationBosnian: "O vi koji vjerujete, učinite pokajanje Allahu iskreno, da bi Gospodar vaš preko ružnih postupaka vaših prešao i da bi vas u džennetske bašče, kroz koje rijeke teku, uveo, na Dan u kojem Allah neće osramotiti Vjerovjesnika i one koji su zajedno sa njim vjerovali; svjetlo njihovo će ići ispred njih i s njihove desne strane. \"Gospodaru naš\" – govoriće oni – \"učini potpunim svjetlo naše i oprosti nam jer Ti, doista, sve možeš.\"",
    category: "rabbana" as DuaCategory,
  },
  {
    id: "66:11",
    surahNumber: 66,
    ayahNumber: 11,
    arabic: "وَضَرَبَ ٱللَّهُ مَثَلًا لِّلَّذِينَ ءَامَنُوا۟ ٱمْرَأَتَ فِرْعَوْنَ إِذْ قَالَتْ رَبِّ ٱبْنِ لِى عِندَكَ بَيْتًا فِى ٱلْجَنَّةِ وَنَجِّنِى مِن فِرْعَوْنَ وَعَمَلِهِۦ وَنَجِّنِى مِنَ ٱلْقَوْمِ ٱلظَّـٰلِمِينَ",
    transliteration: "Wadaraba Allahu mathalan lillatheenaamanoo imraata firAAawna ith qalat rabbiibni lee AAindaka baytan fee aljannati wanajjinee min firAAawnawaAAamalihi wanajjinee mina alqawmi aththalimeen",
    translationBosnian: "A onima koji vjeruju – Allah kao pouku navodi ženu faraonovu, kad je rekla: \"Gospodaru moj, sagradi mi kod Sebe kuću u Džennetu i spasi me od faraona i mučenja njegova, i izbavi me od naroda nepravednog!\"",
    category: "family" as DuaCategory,
  },
  {
    id: "71:28",
    surahNumber: 71,
    ayahNumber: 28,
    arabic: "رَّبِّ ٱغْفِرْ لِى وَلِوَٰلِدَىَّ وَلِمَن دَخَلَ بَيْتِىَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَٱلْمُؤْمِنَـٰتِ وَلَا تَزِدِ ٱلظَّـٰلِمِينَ إِلَّا تَبَارًۢا",
    transliteration: "Rabbi ighfir lee waliwalidayyawaliman dakhala baytiya mu/minan walilmu/mineena walmu/minatiwala tazidi aththalimeena illatabaran",
    translationBosnian: "Gospodaru moj, oprosti meni, i roditeljima mojim, i onome koji kao vjernik u dom moj uđe, i vjernicima i vjernicama, a nevjernicima samo propast povećaj!\"",
    category: "forgiveness" as DuaCategory,
  },
];

const CATEGORIES: DuaCategory[] = [
  "forgiveness",
  "knowledge",
  "guidance",
  "patience",
  "family",
  "rabbana",
];

export function getDuasByCategory(category: DuaCategory): QuranicDua[] {
  return QURANIC_DUAS.filter((d) => d.category === category);
}

export const DUAS_BY_CATEGORY: Record<DuaCategory, QuranicDua[]> =
  Object.fromEntries(
    CATEGORIES.map((cat) => [cat, getDuasByCategory(cat)])
  ) as Record<DuaCategory, QuranicDua[]>;
