import type {
  ChapterAudioData,
  VerseTimestamp,
  WordData,
  WordTimingSegment,
} from "@/types/wordByWord";
import surahs from "@/data/surahs.json";

type SurahMeta = { surahNumber: number; slug: string };
const SURAH_BY_NUMBER = new Map<number, SurahMeta>(
  (surahs as SurahMeta[]).map((s) => [s.surahNumber, s]),
);

function padded(n: number): string {
  return String(n).padStart(3, "0");
}

const chapterAudioCache = new Map<number, ChapterAudioData>();
const wordDataCache = new Map<number, Map<string, WordData[]>>();

interface RawTimestamp {
  verseKey: string;
  timestampFrom: number;
  timestampTo: number;
  segments?: { wordPosition: number; startMs: number; endMs: number }[];
}

interface RawChapterAudio {
  chapterId: number;
  audioUrl: string;
  timestamps: RawTimestamp[];
}

function mapTimestamp(ts: RawTimestamp): VerseTimestamp {
  return {
    verseKey: ts.verseKey,
    timestampFrom: ts.timestampFrom,
    timestampTo: ts.timestampTo,
    segments: (ts.segments ?? []).map(
      (s): WordTimingSegment => ({
        wordPosition: s.wordPosition,
        startMs: s.startMs,
        endMs: s.endMs,
      }),
    ),
  };
}

/**
 * Loads chapter audio data (verse timestamps + word-level segments) from the
 * static-built JSON in /public/data/chapter-audio/. Generated by
 * scripts/generate-chapter-audio-json.ts from Quran.com API at build time.
 */
export async function fetchChapterAudioData(
  surahNumber: number,
): Promise<ChapterAudioData> {
  const cached = chapterAudioCache.get(surahNumber);
  if (cached) return cached;

  const meta = SURAH_BY_NUMBER.get(surahNumber);
  if (!meta) {
    throw new Error(`Unknown surah ${surahNumber}`);
  }
  const url = `/data/chapter-audio/${padded(surahNumber)}-${meta.slug}.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Chapter audio fetch failed: ${response.status}`);
  }
  const raw = (await response.json()) as RawChapterAudio;
  const result: ChapterAudioData = {
    chapterId: raw.chapterId,
    audioUrl: raw.audioUrl,
    timestamps: raw.timestamps.map(mapTimestamp),
  };
  chapterAudioCache.set(surahNumber, result);
  return result;
}

/**
 * Returns chapter-level word data per verse (including verse-end markers).
 * Currently disabled in static-only build — chapter word-by-word rendering
 * falls back to per-ayah word data (which works for all 114 surahs from
 * /data/words/). To re-enable, add a chapter-words generator script.
 */
export async function fetchWordData(
  _surahNumber: number,
): Promise<Map<string, WordData[]>> {
  void _surahNumber;
  return new Map();
}

export function clearWordTimingCache(): void {
  chapterAudioCache.clear();
  wordDataCache.clear();
}
