import type { AllahName } from "@/types/names";

/**
 * 99 Allahovih imena (Al-Asmāʾ al-Ḥusnā) – arapski, transliteracija i prijevod na bosanski.
 */
export const ALLAH_NAMES: AllahName[] = [
  { index: 1, arabic: "ٱلْرَّحْمَـانُ", transliteration: "Ar-Rahman", translationBosnian: "Milostivi" },
  { index: 2, arabic: "ٱلْرَّحِيْمُ", transliteration: "Ar-Rahim", translationBosnian: "Milosrdni" },
  { index: 3, arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", translationBosnian: "Vladar" },
  { index: 4, arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", translationBosnian: "Sveti" },
  { index: 5, arabic: "ٱلسَّلَامُ", transliteration: "As-Salam", translationBosnian: "Mir" },
  { index: 6, arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", translationBosnian: "Vjerovjesnik sigurnosti" },
  { index: 7, arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", translationBosnian: "Zaštitnik" },
  { index: 8, arabic: "ٱلْعَزِيزُ", transliteration: "Al-Aziz", translationBosnian: "Moćni" },
  { index: 9, arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", translationBosnian: "Silni" },
  { index: 10, arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", translationBosnian: "Nadmoćni" },
  { index: 11, arabic: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", translationBosnian: "Stvoritelj" },
  { index: 12, arabic: "ٱلْبَارِئُ", transliteration: "Al-Bari'", translationBosnian: "Stvaralac" },
  { index: 13, arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", translationBosnian: "Obličar" },
  { index: 14, arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", translationBosnian: "Oprostitelj" },
  { index: 15, arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", translationBosnian: "Nadmoćni (koji potčinjava)" },
  { index: 16, arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", translationBosnian: "Darovalac" },
  { index: 17, arabic: "ٱلْرَّزَّاقُ", transliteration: "Ar-Razzaq", translationBosnian: "Opskrbljivač" },
  { index: 18, arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", translationBosnian: "Otvaratelj" },
  { index: 19, arabic: "ٱلْعَلِيمُ", transliteration: "Al-Alim", translationBosnian: "Sveznajući" },
  { index: 20, arabic: "ٱلْقَابِضُ", transliteration: "Al-Qabid", translationBosnian: "Onaj koji steže" },
  { index: 21, arabic: "ٱلْبَاسِطُ", transliteration: "Al-Basit", translationBosnian: "Onaj koji širi" },
  { index: 22, arabic: "ٱلْخَافِضُ", transliteration: "Al-Khafid", translationBosnian: "Ponižavatelj" },
  { index: 23, arabic: "ٱلْرَّافِعُ", transliteration: "Ar-Rafi'", translationBosnian: "Uzvisitelj" },
  { index: 24, arabic: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", translationBosnian: "Poštovatelj" },
  { index: 25, arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", translationBosnian: "Ponižavatelj" },
  { index: 26, arabic: "ٱالسَّمِيعُ", transliteration: "As-Sami'", translationBosnian: "Svečujući" },
  { index: 27, arabic: "ٱلْبَصِيرُ", transliteration: "Al-Basir", translationBosnian: "Svevideći" },
  { index: 28, arabic: "ٱلْحَكَمُ", transliteration: "Al-Hakam", translationBosnian: "Sudija" },
  { index: 29, arabic: "ٱلْعَدْلُ", transliteration: "Al-Adl", translationBosnian: "Pravedni" },
  { index: 30, arabic: "ٱللَّطِيفُ", transliteration: "Al-Latif", translationBosnian: "Nježni" },
  { index: 31, arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabir", translationBosnian: "Sveznajući" },
  { index: 32, arabic: "ٱلْحَلِيمُ", transliteration: "Al-Halim", translationBosnian: "Blagi" },
  { index: 33, arabic: "ٱلْعَظِيمُ", transliteration: "Al-Azim", translationBosnian: "Veličanstveni" },
  { index: 34, arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafur", translationBosnian: "Oprostivi" },
  { index: 35, arabic: "ٱلْشَّكُورُ", transliteration: "Ash-Shakur", translationBosnian: "Zahvalni" },
  { index: 36, arabic: "ٱلْعَلِيُّ", transliteration: "Al-Ali", translationBosnian: "Uzvišeni" },
  { index: 37, arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabir", translationBosnian: "Veliki" },
  { index: 38, arabic: "ٱلْحَفِيظُ", transliteration: "Al-Hafiz", translationBosnian: "Čuvar" },
  { index: 39, arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqit", translationBosnian: "Opskrbljivač" },
  { index: 40, arabic: "ٱلْحَسِيبُ", transliteration: "Al-Hasib", translationBosnian: "Računovoda" },
  { index: 41, arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jalil", translationBosnian: "Veličanstveni" },
  { index: 42, arabic: "ٱلْكَرِيمُ", transliteration: "Al-Karim", translationBosnian: "Plemeniti" },
  { index: 43, arabic: "ٱلْرَّقِيبُ", transliteration: "Ar-Raqib", translationBosnian: "Nadzornik" },
  { index: 44, arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujib", translationBosnian: "Odgovarajući" },
  { index: 45, arabic: "ٱالْوَاسِعُ", transliteration: "Al-Wasi'", translationBosnian: "Sveobuhvatni" },
  { index: 46, arabic: "ٱلْحَكِيمُ", transliteration: "Al-Hakim", translationBosnian: "Mudri" },
  { index: 47, arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadud", translationBosnian: "Ljubavni" },
  { index: 48, arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majid", translationBosnian: "Slavni" },
  { index: 49, arabic: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", translationBosnian: "Onaj koji oživljava" },
  { index: 50, arabic: "ٱلْشَّهِيدُ", transliteration: "Ash-Shahid", translationBosnian: "Svjedok" },
  { index: 51, arabic: "ٱلْحَقُّ", transliteration: "Al-Haqq", translationBosnian: "Istina" },
  { index: 52, arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakil", translationBosnian: "Pouzdanik" },
  { index: 53, arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", translationBosnian: "Snažni" },
  { index: 54, arabic: "ٱلْمَتِينُ", transliteration: "Al-Matin", translationBosnian: "Čvrsti" },
  { index: 55, arabic: "ٱلْوَلِيُّ", transliteration: "Al-Wali", translationBosnian: "Zaštitnik" },
  { index: 56, arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hamid", translationBosnian: "Hvaljeni" },
  { index: 57, arabic: "ٱلْمُحْصِي", transliteration: "Al-Muhsi", translationBosnian: "Onaj koji broji" },
  { index: 58, arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi'", translationBosnian: "Početnik" },
  { index: 59, arabic: "ٱلْمُعِيدُ", transliteration: "Al-Mu'id", translationBosnian: "Onaj koji vraća" },
  { index: 60, arabic: "ٱلْمُحْيِي", transliteration: "Al-Muhyi", translationBosnian: "Oživljavatelj" },
  { index: 61, arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumit", translationBosnian: "Onaj koji daje smrt" },
  { index: 62, arabic: "ٱلْحَيُّ", transliteration: "Al-Hayy", translationBosnian: "Živi" },
  { index: 63, arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyum", translationBosnian: "Samoopstojeći" },
  { index: 64, arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", translationBosnian: "Onaj koji nalazi" },
  { index: 65, arabic: "ٱلْمَاجِدُ", transliteration: "Al-Majid", translationBosnian: "Slavni" },
  { index: 66, arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", translationBosnian: "Jedini" },
  { index: 67, arabic: "ٱلْأَحَدُ", transliteration: "Al-Ahad", translationBosnian: "Jedan" },
  { index: 68, arabic: "ٱلْصَّمَدُ", transliteration: "As-Samad", translationBosnian: "Samodovoljni" },
  { index: 69, arabic: "ٱلْقَادِرُ", transliteration: "Al-Qadir", translationBosnian: "Sposobni" },
  { index: 70, arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", translationBosnian: "Moćni" },
  { index: 71, arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", translationBosnian: "Onaj koji iznosi naprijed" },
  { index: 72, arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", translationBosnian: "Onaj koji odgada" },
  { index: 73, arabic: "ٱلْأَوَّلُ", transliteration: "Al-Awwal", translationBosnian: "Prvi" },
  { index: 74, arabic: "ٱلْآخِرُ", transliteration: "Al-Akhir", translationBosnian: "Posljednji" },
  { index: 75, arabic: "ٱلْظَّاهِرُ", transliteration: "Az-Zahir", translationBosnian: "Očiti" },
  { index: 76, arabic: "ٱلْبَاطِنُ", transliteration: "Al-Batin", translationBosnian: "Skriveni" },
  { index: 77, arabic: "ٱلْوَالِي", transliteration: "Al-Wali", translationBosnian: "Zaštitnik" },
  { index: 78, arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", translationBosnian: "Uzvišeni" },
  { index: 79, arabic: "ٱلْبَرُّ", transliteration: "Al-Barr", translationBosnian: "Dobročinitelj" },
  { index: 80, arabic: "ٱلْتَوَابُ", transliteration: "At-Tawwab", translationBosnian: "Primatelj pokajanja" },
  { index: 81, arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", translationBosnian: "Osvetnik" },
  { index: 82, arabic: "ٱلْعَفُوُّ", transliteration: "Al-Afuww", translationBosnian: "Oprostivi" },
  { index: 83, arabic: "ٱلْرَّءُوفُ", transliteration: "Ar-Ra'uf", translationBosnian: "Milostivi" },
  { index: 84, arabic: "مَالِكُ ٱلْمُلْكِ", transliteration: "Malik al-Mulk", translationBosnian: "Vladar carstva" },
  { index: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ", transliteration: "Dhu al-Jalal wa al-Ikram", translationBosnian: "Posjednik veličanstvenosti i časti" },
  { index: 86, arabic: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", translationBosnian: "Pravedni" },
  { index: 87, arabic: "ٱلْجَامِعُ", transliteration: "Al-Jami'", translationBosnian: "Sakupljač" },
  { index: 88, arabic: "ٱلْغَنِيُّ", transliteration: "Al-Ghani", translationBosnian: "Bogati" },
  { index: 89, arabic: "ٱلْمُغْنِي", transliteration: "Al-Mughni", translationBosnian: "Obogaćivač" },
  { index: 90, arabic: "ٱلْمَانِعُ", transliteration: "Al-Mani'", translationBosnian: "Onaj koji sprječava" },
  { index: 91, arabic: "ٱلْضَّارُ", transliteration: "Ad-Darr", translationBosnian: "Onaj koji nanosi štetu" },
  { index: 92, arabic: "ٱلْنَّافِعُ", transliteration: "An-Nafi'", translationBosnian: "Korisni" },
  { index: 93, arabic: "ٱلْنُّورُ", transliteration: "An-Nur", translationBosnian: "Svjetlo" },
  { index: 94, arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", translationBosnian: "Vodič" },
  { index: 95, arabic: "ٱلْبَدِيعُ", transliteration: "Al-Badi'", translationBosnian: "Jedinstveni stvaralac" },
  { index: 96, arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", translationBosnian: "Vječni" },
  { index: 97, arabic: "ٱلْوَارِثُ", transliteration: "Al-Warith", translationBosnian: "Nasljednik" },
  { index: 98, arabic: "ٱلْرَّشِيدُ", transliteration: "Ar-Rashid", translationBosnian: "Vodič na pravom putu" },
  { index: 99, arabic: "ٱلْصَّبُورُ", transliteration: "As-Sabur", translationBosnian: "Strpljivi" },
];
